version: '3'
services:
  wol-client:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: wol-client
    ports:
      - '8080:80'
      - '8443:443'
      - '6001:6001' # Websocket server
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://localhost:8080
      - TZ=Europe/Berlin
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './data/config:/config' # Directory for sqlite database & .env
      - './data/ssl/web:/etc/ssl/web' # Directory for ssl certificates
    image: wol-client
    restart: unless-stopped
