version: '3'
services:
  waky:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: waky
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://localhost
      - TZ=Europe/Berlin
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './data/config:/config' # Directory for sqlite database & .env
      - './data/ssl/web:/etc/ssl/web' # Directory for ssl certificates
    image: waky
    network_mode: host
    restart: unless-stopped
