#!/command/with-contenv bash

# Exit on error
set -e

echo ""
echo "🐇  Configuring Template..."
echo ""

# Fix permissions
echo "🔒  Fixing app path file permissions..."
chmod -R 755 /config
chown -R webuser:webgroup /config
chown -R webuser:webgroup $WEBUSER_HOME
echo "✅  Permissions fixed."
echo ""

if [ ${DB_CONNECTION:="sqlite"} = "sqlite" ]; then
    # Check for database
    if [ ! -f /config/database.sqlite ]; then
        echo "🙄  SQLite database not found, creating..."
        s6-setuidgid webuser touch /config/database.sqlite
        echo "✅  SQLite database created."
    else
        echo "✅  Database already exists."
    fi
    echo ""

    # create symlinks
    echo "🔗  Creating database symlink..."
    symlinks=( \
    /var/www/html/database/database.sqlite \
    )

    for i in "${symlinks[@]}"
    do
        if [[ -e "$i" && ! -L "$i" ]]; then
            rm -rf "$i"
        fi
        if [[ ! -L "$i" ]]; then
            ln -s /config/"$(basename "$i")" "$i"
        fi
    done

    echo "✅  Database symlink created."
    echo ""
fi

# Check for env file
if [ ! -f /config/.env ]; then
    echo "🙄  Environment file not found, creating..."
    s6-setuidgid webuser cp $WEBUSER_HOME/.env.prod.example /config/.env
    echo "✅  Environment file created."
else
    echo "✅  Environment file exists."
fi

echo ""

# create symlinks
echo "🔗  Creating symlinks for config and log files..."
symlinks=( \
/var/www/html/.env \
/var/www/html/storage/logs/laravel.log
)

for i in "${symlinks[@]}"
do
    if [[ -e "$i" && ! -L "$i" ]]; then
        rm -rf "$i"
    fi
    if [[ ! -L "$i" ]]; then
        ln -s /config/"$(basename "$i")" "$i"
    fi
done

echo "✅  Symlinks created."
echo ""

# Check for app key
if grep -E "^APP_KEY=[^0-9A-Za-z:+\/=]{1,}" $WEBUSER_HOME/.env > /dev/null; then
    echo "✅  App key exists"
else
    echo "⏳  Generating app key..."
    s6-setuidgid webuser php $WEBUSER_HOME/artisan key:generate --no-ansi -q
    echo "✅  App key generated."
fi

echo ""

# create storage symlink
echo "🔐  Linking the storage..."
s6-setuidgid webuser php $WEBUSER_HOME/artisan storage:link --no-ansi -q
echo "✅  Storage linked."
echo ""

# Build cache
echo "💰  Building the cache..."
s6-setuidgid webuser php $WEBUSER_HOME/artisan config:cache --no-ansi -q
s6-setuidgid webuser php $WEBUSER_HOME/artisan route:cache --no-ansi -q
s6-setuidgid webuser php $WEBUSER_HOME/artisan view:cache --no-ansi -q
echo "✅  Cache set."
echo ""

# Migrate database
echo "🚛  Migrating the database..."
s6-setuidgid webuser php $WEBUSER_HOME/artisan migrate --force --no-ansi -q
echo "✅  Database migrated."
echo ""

# Seed admin user
echo "🚛  Creating the admin user..."
s6-setuidgid webuser php $WEBUSER_HOME/artisan db:seed --force --no-ansi -q
s6-setuidgid webuser php $WEBUSER_HOME/artisan db:seed --class FirstAdminUserSeeder --force --no-ansi -q
echo "✅ Admin user created."
echo ""

# Replace ports. Needed as the project is running in network_mode: host which doesn't support mapping ports.
# The nginx files have to be modified manually.
#
# Creates:
# - http.conf.bak      https.conf.bak      (Original files)
# - http.conf.template https.conf.template (Files with port variables to replace)
# - http.conf          https.conf          (Files used by the webserver, recreated each start)
echo "Replacing ports..."

if [ ! -f "/etc/nginx/site-opts.d/http.conf.bak" ] || [ ! -f "/etc/nginx/site-opts.d/http.conf.template" ]; then
    cp /etc/nginx/site-opts.d/http.conf /etc/nginx/site-opts.d/http.conf.bak
    cp /etc/nginx/site-opts.d/http.conf /etc/nginx/site-opts.d/http.conf.template

    # Replace the port "80" with "${HTTP_PORT}" in the file
    sed -i 's/listen 80 default_server;/listen ${HTTP_PORT} default_server;/' /etc/nginx/site-opts.d/http.conf.template
    sed -i 's/listen \[::\]:80 default_server;/listen [::]:${HTTP_PORT} default_server;/' /etc/nginx/site-opts.d/http.conf.template
fi

if [ ! -f "/etc/nginx/site-opts.d/https.conf.bak" ] || [ ! -f "/etc/nginx/site-opts.d/https.conf.template" ]; then
    cp /etc/nginx/site-opts.d/https.conf /etc/nginx/site-opts.d/https.conf.bak
    cp /etc/nginx/site-opts.d/https.conf /etc/nginx/site-opts.d/https.conf.template

    # Replace the port "443" with "${HTTPS_PORT}" in the file
    sed -i 's/listen 443 http2 ssl default_server;/listen ${HTTPS_PORT} http2 ssl default_server;/' /etc/nginx/site-opts.d/https.conf.template
    sed -i 's/listen \[::\]:443 http2 ssl default_server;/listen [::]:${HTTPS_PORT} http2 ssl default_server;/' /etc/nginx/site-opts.d/https.conf.template
fi

if [[ -z "$HTTP_PORT" ]]; then
    echo "No overridden HTTP port found. Using default config."

    cp /etc/nginx/site-opts.d/http.conf.bak /etc/nginx/site-opts.d/http.conf
else 
    echo "Replacing HTTP Port with $HTTP_PORT"

    envsubst '$$HTTP_PORT' < /etc/nginx/site-opts.d/http.conf.template > /etc/nginx/site-opts.d/http.conf
fi

if [[ -z "$HTTPS_PORT" ]]; then
    echo "No overridden HTTPS port found. Using default config."

    cp /etc/nginx/site-opts.d/https.conf.bak /etc/nginx/site-opts.d/https.conf
else 
    echo "Replacing HTTPS Port with $HTTPS_PORT"

    envsubst '$$HTTPS_PORT' < /etc/nginx/site-opts.d/https.conf.template > /etc/nginx/site-opts.d/https.conf
fi

echo "✅ Ports replaced."
echo ""

# App install done, show a message
echo "✅  All set, Template started."
echo ""
